### ISSUE TITLE
Missing dependency on OMV3

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#11]
Hi, 

Trying OMV3 (3.0.13) and during the dpkg installation I'm getting that "apt-transport-https" is not installed. If I installed it package installation is successful.

Note: I didn't know if I should fill it here or as OMV3 issue.

**Comment by ryecoaaron** [comment]
Most plugins have dependencies.  Using dpkg will never resolve those.  The dpkg output tells you that you probably need to execute apt-get -f install to fix.  There is a guide on this in the forum as well - http://forums.openmediavault.org/index.php/Thread/5549-OMV-Extras-org-Plugin/.  That thread even mentions that you will probably see an apt-transport-https error.
