### ISSUE TITLE
Syncthing repo not working with OMV3

### ISSUE THREAD

**Issue by fanthos** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#12]
In file:
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/etc/omvextras/default_repos.xml#L71

``` <repo2>deb http://apt.syncthing.net/ syncthing release</repo2>```
should be replaced by
``` <repo2>http://apt.syncthing.net/ syncthing release</repo2>```

**Comment by ryecoaaron** [comment]
You are right.  Fixing now.  Thanks!

**Comment by ryecoaaron** [comment]
Fixed in 3.3.1 in repo now.
