### ISSUE TITLE
Error installing Sabnzbd

### ISSUE THREAD

**Issue by ludalito** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#15]
I get an error during the install of openmediavault-sabnzbd

> Sélection du paquet openmediavault-sabnzbd précédemment désélectionné.
(Lecture de la base de données... 32037 fichiers et répertoires déjà installés.)
Dépaquetage de openmediavault-sabnzbd (à partir de .../openmediavault-sabnzbd_1.0.5_all.deb) ...
Traitement des actions différées (« triggers ») pour « openmediavault »...
Restarting engine daemon ...
Paramétrage de openmediavault-sabnzbd (1.0.5) ...
Adding sabnzbd user...
dpkg: erreur de traitement de openmediavault-sabnzbd (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 4
Traitement des actions différées (« triggers ») pour « openmediavault »...
Restarting engine daemon ...
Des erreurs ont été rencontrées pendant l'exécution :
 openmediavault-sabnzbd
Creating index of upgradeable packages ...
Creating index of openmediavault plugins ...
E: Sub-process /usr/bin/dpkg returned an error code (1)

I found the origin of the problem. In the script /var/lib/dpkg/info/openmediavault-sabnzbd.postinst, the latest version of sabnzbd is found by downloading a file from sourceforge. The grep works fine but the sed don't isolate the right string of the version.

**Comment by cptjhmiller** [comment]
Because you are using 1.0.5 of the plugin, you need to install the latest version 1.0.10

**Comment by ludalito** [comment]
I installed the package : openmediavault-omvextrasorg_latest_all I found here : http://omv-extras.org/simple/index.php?id=how-to-install-omv-extras-plugin

**Comment by cptjhmiller** [comment]
You need to enable the download managers testing repo for the other versions to show, The stable version is no longer stable and I can't change that until we have a new stable version or another Dev has time to do it.

**Comment by ryecoaaron** [comment]
This really should be an issue on the sabnzbd issues page - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd/issues
