### ISSUE TITLE
Process list CPU usage sorting issue

### ISSUE THREAD

**Issue by dt64** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#17]
in GUI -> System Information -> Proces List:
if clicked on "% CPU" coloumn to sort descending for CPU utilization the sorting order doesn't work as expected.
it doesn't seem to sort by full values but digit-by-digit, e.g. 2.1, 155, 15.4, 1,5, 0.6 etc.
Screenshot attached.
![omv bug screenshot](https://cloud.githubusercontent.com/assets/23746520/20635301/c1067e72-b35b-11e6-9abe-56461cbbb0a9.JPG)

**Comment by ryecoaaron** [comment]
This tab has been dropped in omv-extras for OMV 3.x and I am only doing security/major bug fixes for OMV 2.x versions.
