### ISSUE TITLE
armel package index missing the 'all' arch related packages 

### ISSUE THREAD

**Issue by rskallies** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#22]
I'm using OVM 4 on an old QNAP TS-412. Adding the repo currently pulls no packages as the Package file on https://dl.bintray.com/openmediavault-plugin-developers/arrakis/dists/stretch/main/binary-armel/Packages contains only the openmediavault-omvextrasorg package.  Some packages does not depend on a specific arch and could possibly used on armel platform.

Changing the line in sources.list from "deb https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch main" to  "deb [armel,amd64] https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch main" allows me to install the platform independently packages. Of course in the GUI there are also listed packages like Virtualbox which will never be run on this arch. Using "apt-cache search openmediavault" listed the missing packages and also showed not the amd64 versions.

**Comment by ryecoaaron** [comment]
This was intentional.  The fact that there is any packages in the repo for armel is an accident.  I don't want to support armel (or powerpc) anymore.
