### ISSUE TITLE
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; cat /boot/grub/grub.cfg | grep ^menuentry' with exit code '1':

### ISSUE THREAD

**Issue by thegitty** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#23]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; cat /boot/grub/grub.cfg | grep ^menuentry' with exit code '1':

See https://bugtracker.openmediavault.org/print_bug_page.php?bug_id=1842

cat: /boot/grub/grub.cfg: No such file or directory

Working with armbian (Cubietruck).

**Comment by ryecoaaron** [comment]
The rpc checking for kernels on i386/amd64 is run before the kernel tab is hidden on arm boards which is what produces the message.  I posted about this in the forum but I haven't got around to fixing it.  Other than clicking on the message, this will cause no problems.

**Comment by ryecoaaron** [comment]
Fixed in 4.1.2 in repo now.
