### ISSUE TITLE
OMV3, openmediavault-zfs: Shared folders going n/a following ZFS pool export

### ISSUE THREAD

**Issue by kalleyne** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#24]
There seems to be a general problem where ZFS pool export results in the resetting of Shared folders to n/a devices. Importation of the pool does not correct the n/a status of devices on Shared folders. SMB clients are affected by this.

There was a discussion about this general issue on this thread:
https://forum.openmediavault.org/index.php/Thread/20364-Shared-folders-going-N-A-for-device-corrupts-USB-Backup/?postID=158505#post158505

Please let me know if you require additional information.
Thanks.

**Comment by kalleyne** [comment]
https://forum.openmediavault.org/index.php/Thread/19861-How-to-correct-shared-folders-going-N-A-for-device-after-ZFS-unmount-remount-Can/

https://forum.openmediavault.org/index.php/Thread/17848-All-shared-folders-lost-Shows-up-as-n-a/

**Comment by ryecoaaron** [comment]
Can you please post this issue on the zfs plugin repo?  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/issues
