### ISSUE TITLE
/binary-armel/packages nearly empty

### ISSUE THREAD

**Issue by franky384** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#25]
Hi there,
the stretch /binary-armel/packages, packages.gz.... are missing all plugins, only 
Package: openmediavault-omvextrasorg
Version: 4.0.0
Architecture: all...
is inside.
omvextras-common is not upgrading to 4.01, omv-backup is not updating and so on.and so on......
Can you fix this, please.

**Comment by subzero79** [comment]
As i understand armel is not supported any more. Users with this arch have to build the packages manually.

**Comment by franky384** [comment]
But i can install and update the plugins without problems if i install them directly via omv-webinterface from the repo at
https://dl.bintray.com/openmediavault-plugin-developers/arrakis/pool/main/
It's working without problems so it would be nice to update the packages lists.
