### ISSUE TITLE
omv-salt stage run all fails

### ISSUE THREAD

**Issue by coffinbearer** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#26]
On a fresh OMV5 Installation after installing the omv-extras plugin the commad `omv-salt stage run all` failes with the following error message:
> ID: run_state_deploy
Function: salt.state
Result: False
Comment: Run failed on minions: debian
Started: 17:33:18.976771
Duration: 5417.139 ms
Changes:
	debian
		Date failed to compile:
	-----------
		Detected conflicting IDs, SLS IDs need to be globally unique.
		The conflicting ID is 'refresh_apt_database' and is found in SLS 'base:omv.deploy.omvextras.default' and SLS 'base:omv.deploy.apt.default'

**Comment by ryecoaaron** [comment]
Fixed in 5.0.3
