### ISSUE TITLE
Using ZFS with OMV 5

### ISSUE THREAD

**Issue by ochorocho** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#29]
Hey, just started using OMV.
Install worked perfectly. Docker install just worked as well.

When i tried setting up ZFS i noticed that is very important to install the proxmox pve kernel first.

Following steps in this order finally worked for me:

* `wget -O - http://omv-extras.org/install | bash`
* System -> OMV-Extras -> Kernel -> Install Proxmox Kernel
* System -> Plugins -> openmediavault-zfs 5.0.1 -> install

Not following this order ~~messed up the apt sources~~ and caused broken dependencies.
Maybe its useful for beginners to prevent install of "openmediavault-zfs" when proxmox kernel is not installed

Anyways, all is working as needed. :-) Thanks.

EDIT: In general it seems like installing 1 plugin at a time is a good idea

**Comment by ryecoaaron** [comment]
The proxmox kernel is not required for zfs.  If you don't use the proxmox kernel, it has to compile the module.  There are plenty of things that can go wrong with compiling modules but I don't want to force users to use the proxmox kernel.

I install multiple plugins quite often.

**Comment by ochorocho** [comment]
Ok, thank you for your quick answer. Makes sense :-)
At the moment i'm happy to use the proxmox kernel.

**Comment by ryecoaaron** [comment]
I use the proxmox kernel myself.
