### ISSUE TITLE
can't add addential docker daemon options like `registry-mirrors`

### ISSUE THREAD

**Issue by Trim21** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#31]
any manual change of `/etc/docker/daemon.json` will be replace by https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/9a198eed9de3bf88ee0a3ebcb88dca79d68446a8/usr/sbin/omv-installdocker#L235-L250

**Comment by ryecoaaron** [comment]
You are reading the code incorrectly. If you leave the path blank in the web interface, you can do whatever you want with the daemon.json file because it won’t do anything with it.
