### ISSUE TITLE
Opt-out of data collection by portainer

### ISSUE THREAD

**Issue by rscircus** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#32]
Portainer mentions in the about page, that they collect data on the user:

```
We at Portainer provide our software free and open source. To understand where best to spend our very limited development budget, we use rudimentary analytics.

## Opt-out

You may opt-out by passing the --no-analytics flag as part of the docker run command when starting Portainer.
If you believe that we could improve our analytics approach make sure to let us know! There is an open discussion on Github.
```

The proposal here is to make use of the phrase: `You may opt-out by passing the --no-analytics flag as part of the docker run command when starting Portainer.` as a default.

**Comment by rscircus** [comment]
As far as I see the change should be made here:

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/464ed5d1899dc1d8ac6bba837eaf5d784d3c1721/usr/sbin/omv-installdocker#L303

**Comment by rscircus** [comment]
Further they use Google Analytics for this. See https://github.com/portainer/portainer/issues/3310 and seem to address the issues though. However, by using this extra the OMV user has no possibility to opt-out. Most recent reaction by the portainer people: https://github.com/portainer/portainer/issues/3310#issuecomment-573511280.

**Comment by ryecoaaron** [comment]
Your pull request makes it impossible to help portainer from the web interface if you don't mind sending them a little data.  And if you read the comment further down (https://github.com/portainer/portainer/issues/3310#issuecomment-573511280), they are going to be switching to their own analytics and it will be **opt-in**.  I will add a switch to opt-in or opt-out.

**Comment by ryecoaaron** [comment]
Implemented in latest commit.

**Comment by rscircus** [comment]
> Your pull request makes it impossible to help portainer from the web interface if you don't mind sending them a little data. And if you read the comment further down ([portainer/portainer#3310 (comment)](https://github.com/portainer/portainer/issues/3310#issuecomment-573511280)), they are going to be switching to their own analytics and it will be **opt-in**. I will add a switch to opt-in or opt-out.

That's what I basically said in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues/32#issuecomment-575899091 and the commit message of https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/pull/33/commits/51bea20bb58484359a4372bacd086f5585841efb.

I'm pretty sure having you opted-in by default is against European law. Thanks for your solution though.

**Comment by ryecoaaron** [comment]
RIght now it is opt out which would have a chance to be against European law but they say the amount of data they collect doesn't warrant opt-in.  They are switching to opt-in anyway which should satisfy the privacy paranoid people.  Either way, I really don't care.  I don't use portainer.  I was just trying to give omv users a docker web interface.  If they collect a little data and it helps keep development going, great.  If they can't keep developing after they don't collect data, it would be a shame that people couldn't donate a little data.
