### ISSUE TITLE
[Cockpit] Store Metrics doesn't work on RPI 4 with raspbian buster

### ISSUE THREAD

**Issue by LizhangX** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#35]
Hi,

I setup OMV 5 and install the update with the OMV-Extra.
However, after I downloaded the cockpit and enabled the store metric, it didn't seem to work.
I raised an issue with Cockpit and they said the version 188 we have here is pretty old and maybe newer version won't have the store metric issue.
Refer: https://github.com/cockpit-project/cockpit/issues/13455

Just wondering if there is going to be support or install for newer versions for Cockpit.
Let me know if I could help getting newer version on board.

Thanks a lot!

**Comment by LizhangX** [comment]
So I kinda poke around and see it is using apt-get to update.

Steps taken:
1. Installed Cockpit without backports, version 188-1
2. Then I enabled backports, seeing communication error after save. Then try to reinstall cockpit, still in 188-1.
2. Disable and re-enable backport, same communication issue, then reboot RPI. After I can see it is in version `208-1~bpo10+1`.
3. However, the issue seems still exist with version 208.

**Comment by ryecoaaron** [comment]
omv-extras does everything it can.  It gives you the option to enable backports and will pin cockpit* if backports is enabled.  If something isn't working within cockpit, that should be a bug report for the debian and/or cockpit teams.

**Comment by LizhangX** [comment]
Cool thanks for the reply.

One think I noticed is that the backports list only works after reboot of the system.
It was replacing the security.list with backports.list in `/etc/apt/sources.list.d` once I enabled backports from UI, and it prompt me a window with "communication error".
After reboot the security.list is then re-appeared.

**Comment by ryecoaaron** [comment]
You don't have to reboot to enable backports.  You just need to do an apt-get update (which can be done from omv-extras).  The communication error is caused by lots of disk i/o from apt-get update.  I would guess your SD card is slow because I don't have these on my RPi4 with an A1 sd card.

**Comment by LizhangX** [comment]
apt-get update only is working fine when triggered from the drop-down. Just when I toggle backports (on and off) and save, it would take a while in the saving window and then give me the error. (Maybe it is trying to update the source list and also do an apt-get update?)

I have the Samsung Evo Plus micro sd card which says class 10 and UHS-1. I couldn't find Samsung cards with A1 ratings thus not sure how big of difference they have. Maybe it is indeed due to the sd card. Any recommendations for which one to buy?
