### ISSUE TITLE
Feature - please allow securing Portainer UI with TLS

### ISSUE THREAD

**Issue by sseide** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#36]
copied from https://github.com/openmediavault/openmediavault/issues/622

It would be really helpful to have a possibility to enables SSL via OMV web UI too as probably most people do not want to go down into the inner depths of the system an use the UI wherever possible. Here it would really help to have a secure system by default (or with one-two extra clicks).

### Description of issue/question
Currently its possible to use OMV5 to run docker containers (very helpful!). As an UI "portainer" is used, but current one-click deployment via OMV web UI does not use TLS to encrypt communication with browser. Please update the portainer installation to use TLS.

### Steps to reproduce issue
activate OMV extras plugin, on the left click on Menu "OMV-Extras", then "Docker" -> "Portainer" -> "Install"
Portainer is installed but can only be used without TLS encryption. Updating docker deployment afterwards to enable TLS is not working.

### Steps to do to enable encryption
As i understand the following steps are needed to use SSL/TLS encryption for the web-ui in portainer.

* Update "OMV-Extras" -> "Docker" web ui, add checkbock "Enable TLS" and dropdown list with all SSL certificates configured within OMV
* Update button to open portainer from OMV web UI to either use HTTP or HTTPS depending on the "Enable TLS" checkbox
* Modify Portainer installation call
  a) bind mount the choosen certificate (key and cert file) into docker container
  b) add command line parameters needed to the docker CMD option to enable ssl (`--ssl --sslcert /tmp/ssl/cert.pem --sslkey /tmp/ssl/cert.key`) - see portainer documentation at https://portainer.readthedocs.io/en/stable/deployment.html#secure-portainer-using-ssl

Depending on how portainer is installed the following changes are needed on portainer installation:
Example with "docker run" command (docker compose file is similiar). For this example i assume the file name of the certificate choosen is "openmediavault-123"
```
docker run -v /etc/ssl/private/openmediavault-123.key:/tmp/ssl/cert.key -v /etc/ssl/certs/openmediavault-123.crt:/tmp/ssl/cert.pem <all other params> /portainer --ssl --sslcert /tmp/ssl/cert.pem --sslkey /tmp/ssl/cert.key
```

### Versions report
OMV 5.3.2-1
omvextrasorg 5.2.4

**Comment by ptruman** [comment]
You can achieve this with Traefik/LetsEncrypt, if you've installed Docker & Portainer.

https://site.gothtech.co.uk/articles/omv-portainer-traefik-letsencrypt#h.78ftzg1j35ng

Not as simple as an install time option in OMV, but gives you total flexibility on the SAN you want to use.

**Comment by ryecoaaron** [comment]
Closed by https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/pull/67
