### ISSUE TITLE
Latest OMV 5 fresh install does not allow omvextras install

### ISSUE THREAD

**Issue by pk1057** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#37]
Hello,
i installed a fresh OMV 5 with the latest version.
When i tried to install omvextras the installer bailed out with unsatisfied requirement for gnupg.
gnupg seems currently uninstallable and is not necessary for dirmngr install.
So i modified the package and removed the requirement for gnupg and rebuild it.
Now the package is installable and i can't find any problems so far.

**Comment by ryecoaaron** [comment]
Thanks for the heads up about gnupg.  This is a leftover requirement from OMV 4.x where you could add repos and keys.  I will remove the dependency but gnupg doesn't hurt anything and should be installable on your system.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/3db94c1eb67d1a4e78963fe803f5600614b06faf
