### ISSUE TITLE
Extras aren't properly installed

### ISSUE THREAD

**Issue by Trottel** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#38]
In OMV5 if I use in Putty "wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash" command, then I get "Repository 'https://dl.bintray.com/openmediavault-plugin-developers/usul buster Release' isn't signed" error and omv-extras doesn't install properly. There are no additional plugins installed.

**Comment by ryecoaaron** [comment]
this is because i had to remove a package from the repo. will have to wait until the release file is regenerated. no where near a computer to do that now.

**Comment by Trottel** [comment]
OK, thanks for the info, I will wait.

**Comment by iJayscn** [comment]
Looking forward to update, thanks

**Comment by gscsnm** [comment]
Looking forward to update, thanks

**Comment by FredSkar** [comment]
@ryecoaaron Any estimation on when this will be done?

**Comment by ryecoaaron** [comment]
When I wakeup........ jeesh.

**Comment by ryecoaaron** [comment]
Repo should be fine now.

**Comment by gscsnm** [comment]
Thanks a bundle.

**Comment by Trottel** [comment]
Now it's OK. Thank you
