### ISSUE TITLE
support for armel debian

### ISSUE THREAD

**Issue by joerg555** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#39]
Please update your armel Packages:
`https://dl.bintray.com/openmediavault-plugin-developers/arrakis/dists/stretch/main/binary-armel/Packeges`
you can copy ist from armhf.
Most of your packages don't use binray packages and it will be ok.
Now i have download the packages from "pool" und try install with 

> dpkg -i

Question ?
you have debian source packages to install via apt source ?
regards Jörg

**Comment by ryecoaaron** [comment]
Nope.  I stopped supporting armel early in OMV 3.x.  They are too slow and while most packages are not arch-specific, some are and I don't want to support armel.
