### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by hitam4450** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#41]
Hi,
first of all many thanks for your efforts to create Plugins to customize OMV in many ways !

However, I would like to see a "Nextcloud" plugin, since i am enthusiastic project member and user of Nextcloud, since the beginning! As soon as the plugin will be made available, I am going to implement OMV onto my new server infrastructure will distribute it to all my customers !

Best regards, hitam4450

**Comment by ryecoaaron** [comment]
Nextcloud can easily be installed in docker - https://forum.openmediavault.org/index.php?thread/23005-installation-and-setup-videos-beginning-intermediate-and-advanced/&postID=179889#post179889

**Comment by hitam4450** [comment]
Thanks for your advice, I do not want to install and use docker !

**Comment by ryecoaaron** [comment]
What is your reason for not wanting docker?  A nextcloud plugin used to exist (owncloud at the time) but it was very difficult to maintain and unnecessary since nextcloud themselves maintain a docker.

**Comment by ryecoaaron** [comment]
What is your reason for not wanting docker?  A nextcloud plugin used to exist (owncloud at the time) but it was very difficult to maintain and unnecessary since nextcloud themselves maintain a docker.
