### ISSUE TITLE
ARMHF: Docker-compose outdated

### ISSUE THREAD

**Issue by fl0r1s** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#43]
The docker-compose version installed by `install-docker` is version 1.21, however, version 1.26 is already available and uses docker-compose schemas > 3.3. 

[The installation lines](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/2fbbb3c5435fbdba1a16c2ddf66297d8c5ab9683/usr/sbin/omv-installdocker#L316-320) show that curl is used for installing docker-compose, but the versions > 1.21 do not have an armhf package.

A post install workaround is to remove the docker compose installation and reinstall using pip3, which does contain the latest version.
```
sudo rm $(which docker-compose) 
sudo apt-get install python3-pip
sudo pip3 install docker-compose
sudo reboot
```

**Comment by ryecoaaron** [comment]
I'm not really a fan of pip. One reason is the uninstall doesn't uninstall dependencies.  Another is it may install dependencies that conflict with installed Debian python packages.  I looked at using the Debian 11 package but it has a bunch of dependencies that would be a pain too.  You also can't just remove the docker-compose file.  You should remove the docker-compose package on non-amd64 systems.  I will look for other options.

**Comment by fl0r1s** [comment]
Since there is no recent communication I will close this issue.

**Comment by ryecoaaron** [comment]
@fl0r1s I forgot about this issue but I did implement a change where armhf and arm64 are using the linux server docker-compose build.  This happened about a month ago - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/b080978e9ca488d21965f1ed65afbc6e7a9d1483
