### ISSUE TITLE
OMV-Extras icon is the only one with non-transparent background

### ISSUE THREAD

**Issue by tooomm** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#44]
<sub>(Moved from https://github.com/openmediavault/openmediavault/issues/771)</sub>

### Description of issue/question
![omve](https://user-images.githubusercontent.com/9874850/88276103-cc437380-ccde-11ea-8514-8538f6f7e00a.png)
Spotted this on Firefox 78.0.2 (Windows) and mobile Safari.

### Steps to reproduce issue
Click on the `Home` icon.

### Versions report
5.5.4-1

**Comment by DavidBerdik** [comment]
I have submitted a pull request to fix this: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/pull/56

**Comment by ryecoaaron** [comment]
Switched to material designs icon in preparation for OMV 6.x where it is required.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/db7b4ec5094ed31587263d37dba4c2423be4aefc
