### ISSUE TITLE
Enable IPv6 in Docker

### ISSUE THREAD

**Issue by pakr-info** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#47]
It would be fine to enable IPv6 for docker when IPv6 is enabled in network configuration or add new option to UI. It is necessary to set "ipv6": true in /etc/docker/daemon.json - https://docs.docker.com/config/daemon/ipv6/

**Comment by ryecoaaron** [comment]
If you leave the docker config path blank, you are able to write your own daemon.json file. This should accommodate any custom features needed.

**Comment by pakr-info** [comment]
Yes, good point. Issue can be closed.
