### ISSUE TITLE
Suggestion to use --no-color in salt stack

### ISSUE THREAD

**Issue by rabelux** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#50]
I previously opened an issue in OMV's fail2ban-repo [(link)](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-fail2ban/issues/28) reporting unexpected characters in the log. If I concluded correctly it should be possible to prevent these colour-characters from occuring in log-files by calling salt with `--no-color` option as votdev did [here](https://github.com/openmediavault/openmediavault/commit/fbf2bda17100f21afceabc88fb3b9556aef62f30)

Screenshot from today's apt-get upgrade:
![grafik](https://user-images.githubusercontent.com/16120882/107623726-13348e80-6c5a-11eb-8280-e677e0691cdf.png)

**Comment by ryecoaaron** [comment]
I actually didn't mean to leave the quiet flag off but I think the output might be useful.  So, I added the no-color flag  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/c51ffc1e2885f1c3b919d45f3fe67d3b3178d867

**Comment by rabelux** [comment]
Thanks!
