### ISSUE TITLE
Allow change apt source

### ISSUE THREAD

**Issue by septs** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#51]
P.R.C China Region there are these mirror sites:

- https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers/
- https://mirrors.bfsu.edu.cn/OpenMediaVault/openmediavault-plugin-developers/

Suggestion to provide the function of change the mirror sites

**Comment by ryecoaaron** [comment]
Neither of those repos are official mirrors. They are also out of date since they are syncing from bintray instead of the new repos on github - https://openmediavault-plugin-developers.github.io/packages/debian.  Plus, omv-extras plugins are so small, is there a problem using the github repo?

**Comment by septs** [comment]
CC @z4yx

**Comment by septs** [comment]
> Plus, omv-extras plugins are so small, is there a problem using the github repo?

1. improve china region user download speed.
2. reduce unavailability, https://en.wikipedia.org/wiki/Censorship_of_GitHub#China

**Comment by ryecoaaron** [comment]
Most of the plugins and the release file are less than 20k.  Is download speed that big of an issue?

I have a mirror on omv-extras.org.  Would that be ok to use?

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/1e63392e413186c95f61dde9d265508d9fc1a7a6

**Comment by ryecoaaron** [comment]
5.5.6 in the repo now.

**Comment by septs** [comment]
OK

**Comment by septs** [comment]
```console
# omv-env set OMVEXTRAS_APT_REPOSITORY_URL https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers/
Key must be prefixed with OMV_
```

**Comment by ryecoaaron** [comment]
I guess I never use omv-env.  I will fix that.

**Comment by ryecoaaron** [comment]
Fixed again https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/ae886174c2d7b724236f664771f7e48940998524
5.5.7 in the repo now.

**Comment by ryecoaaron** [comment]
Docker and teamviewer URLs
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/99264011f9033fd4724a596de3d3ad4f09f88d09

**Comment by ZenithalHourlyRate** [comment]
> They are also out of date since they are syncing from bintray instead of the new repos on github - https://openmediavault-plugin-developers.github.io/packages/debian.

Upstream for `openmediavault-plugin-developers` was updated to this suggested URL by commit https://github.com/tuna/tunasync-scripts/commit/3a33d4e152e3565c0a4dd0b89f0966316a9f2df0, and we have deployed this script.

**Comment by ryecoaaron** [comment]
@ZenithalHourlyRate there is no armel repos for omv-extras and there is no need to sync erasmus* (omv 3.x) repos anymore since they are EOL'd.  Probably no reason to sync arrakis (omv 4.x) repos either.

**Comment by ZenithalHourlyRate** [comment]
> @ZenithalHourlyRate there is no armel repos for omv-extras and there is no need to sync erasmus* (omv 3.x) repos anymore since they are EOL'd. Probably no reason to sync arrakis (omv 4.x) repos either.

cc @z4yx
