### ISSUE TITLE
Stacks using the compose option 'build:' with local contexts fail to deploy

### ISSUE THREAD

**Issue by Konnichy** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#54]
Hello,

The Compose file option [`build:`](https://docs.docker.com/compose/compose-file/compose-file-v3/#build) allows to build the image to deploy by pointing to a custom build context (Dockerfile + external files to integrate into the image).

To do this, docker-compose sends the build context to Docker, which then builds the image. However, when using Portainer in a Docker container, the containerized `docker-compose` binary fails to retrieve the context because it doesn't have access to files outside the `portainer` container.
The solution I could imagine would be to add an advanced parameter in the OMV GUI that would add a `--volume` argument when starting Portainer to give it access to the user's build contexts.

I successfully made it work with the following patch:
```
--- /usr/sbin/omv-installdocker.orig    2021-04-11 17:55:23.486110592 +0000
+++ /usr/sbin/omv-installdocker 2021-04-11 17:56:34.179274426 +0000
@@ -410,7 +410,7 @@

   # pull and start portainer
   echo "Pulling and starting ${portainerImage} ..."
-  docker run -d --name "${portainerName}" -p ${webport}:9000 -p ${agentport}:8000 --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v ${portainerVolume}:/data ${portainerImage}
+  docker run -d --name "${portainerName}" -p ${webport}:9000 -p ${agentport}:8000 --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v ${portainerVolume}:/data -v /srv/dev-disk-by-uuid-abcd1234-1234-1234-1234-abcdef123456/path/to/my/build-contexts:/build-contexts ${portainerImage}
   if [ $? -gt 0 ]; then
     echo "Something went wrong trying to pull and start portainer ..."
   fi
```

It then becomes possible to use the following compose file option for example:
```
build: /build-contexts/my-service-1
```
Thank you

**Comment by ryecoaaron** [comment]
This doesn't seem to be needed by the most OMV users.  I can't even find that volume referenced in the official docs.  Is there a reason you can't build the image with compose and then just use the image from portainer?

**Comment by Konnichy** [comment]
I arbitrarily named the volume "/build-contexts". It won't appear in any doc under this name.

I guess I could build the image outside of Portainer, although it kind of defeats a little the purpose of having a GUI.
There is also the possibility to tar the build context and build an image by uploading it to the GUI. But this does not allow using the "App Templates" feature to the fullest.

**Comment by ryecoaaron** [comment]
You could just install portainer from command line with your arguments and then use the portainer gui for everything else.  I want the options to be very simple for the average OMV user.  Even with the advanced check hiding some options, I don't want those too complex.  I would guess 99.5% of OMV users will never build an image.

**Comment by Konnichy** [comment]
Sure, you're right.
You may however consider an "extra arguments" advanced option. That may allow solving this and some other needs, such as adding `--no-analytics` or TLS arguments as I saw in other issue tickets.
Thank you for your support.
