### ISSUE TITLE
"No function provided" in pkg.refresh_db

### ISSUE THREAD

**Issue by kngharv** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#55]
newbie in openmediavault here.

I just fresh installed OMV on my new proxmox system.   No legacy stuff whatsoever.

However, when I tried to install omvextra, I got the following error when I execute the following:

sudo omv-salt deploy run omvextras

> ----------
>           ID: refresh_database_apt
>     Function: module.run
>         Name: pkg.refresh_db
>       Result: False
>      Comment: No function provided.
>      Started: 18:13:28.388345
>     Duration: 0.547 ms
>      Changes:   
> 
> Summary for debian
> ------------
> Succeeded: 6
> Failed:    1
> ------------
> Total states run:     7
> Total run time: 351.150 ms

Any pointers on how to resolve this and/or give me a pointer on providing more useful information so people here can help me to resolve this bug?

thanks in advance

**Comment by marnunez** [comment]
Hi! Same  here. Tried to use the 5.6 deb file, same results

**Comment by subzero79** [comment]
Did you actually installed omv into a proxmox host or into a proxmox guest? The first one is a no go. Try leave proxmox pristine

**Comment by kngharv** [comment]
> Did you actually installed omv into a proxmox host or into a proxmox guest? The first one is a no go. Try leave proxmox pristine

I created a VM using omv's iso file.  Does that answer your question?  

Thanks

**Comment by jolu1705** [comment]
Same here!

**Comment by ryecoaaron** [comment]
That last command that is failing is an apt-get update. One of your repos is failing. Unless I see the output of apt-get update, I can’t help. I asked for this on a couple of threads on the forum.

**Comment by jolu1705** [comment]
I have generated a log of apt-get update and attached it. 
If you need more logfiles or info, please tell me.
[log.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/files/6376346/log.txt)

**Comment by kngharv** [comment]
> # apt update
> Get:1 file:/var/cache/openmediavault/archives  InRelease
> Ign:1 file:/var/cache/openmediavault/archives  InRelease
> Get:2 file:/var/cache/openmediavault/archives  Release
> Ign:2 file:/var/cache/openmediavault/archives  Release
> Get:3 file:/var/cache/openmediavault/archives  Packages
> Ign:3 file:/var/cache/openmediavault/archives  Packages
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages
> Ign:3 file:/var/cache/openmediavault/archives  Packages
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages
> Ign:3 file:/var/cache/openmediavault/archives  Packages
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages
> Ign:3 file:/var/cache/openmediavault/archives  Packages
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages
> Ign:3 file:/var/cache/openmediavault/archives  Packages
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages      
> Ign:3 file:/var/cache/openmediavault/archives  Packages      
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Get:3 file:/var/cache/openmediavault/archives  Packages      
> Get:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Ign:4 file:/var/cache/openmediavault/archives  Translation-en_US
> Get:5 file:/var/cache/openmediavault/archives  Translation-en
> Ign:5 file:/var/cache/openmediavault/archives  Translation-en
> Hit:6 http://deb.debian.org/debian buster InRelease          
> Hit:7 http://security.debian.org/debian-security buster/updates InRelease                              
> Get:8 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]                                  
> Hit:9 https://download.docker.com/linux/debian buster InRelease                                        
> Hit:10 https://openmediavault.github.io/packages usul InRelease                                        
> Hit:11 https://openmediavault-plugin-developers.github.io/packages/debian usul InRelease
> Hit:12 http://linux.teamviewer.com/deb stable InRelease
> Get:13 http://httpredir.debian.org/debian buster-backports InRelease [46.7 kB]
> Hit:14 http://packages.openmediavault.org/public usul InRelease
> Fetched 98.6 kB in 2s (60.5 kB/s)
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.

"apt update" seems fine.  No error, no warning.

**Comment by ryecoaaron** [comment]
Then the omv salt packages might have removed something needed for this command to work. I am just getting up and have to respons to lots of these posts. give me a bit

**Comment by jolu1705** [comment]
I guess its a script error or missing dependency

**Comment by ryecoaaron** [comment]
It wasnt a code issue previously.

**Comment by ryecoaaron** [comment]
It isn’t running a script. It is using a native salt function to update repos. If that function was removed from the salt packages, there is nothing the plugin can do. I would have to change the code.

**Comment by jolu1705** [comment]
> It isn’t running a script. It is using a native salt function to update repos. If that function was removed from the salt packages, there is nothing the plugin can do. I would have to change the code.

How can we help?

**Comment by ryecoaaron** [comment]
Wait for me to finish getting ready for the day so I can test on my systems.

**Comment by ryecoaaron** [comment]
The pkg.refresh_db function was removed from the latest saltstack packages Volker built. 
 If he didn't remove the function (which is still shown in the docs https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.aptpkg.html), then I will have to come up with a solution that doesn't involve native salt code (not hard).  The problem is people will have to manually install the update.  What  a mess.

**Comment by jolu1705** [comment]
I have seen that you tried to reach out to Volker on the OMV forum. Let's see if he reacts and when :-)

**Comment by ryecoaaron** [comment]
Interesting... OMV itself is using the same function.  So, even if I changed omv-extras code, OMV would still be broken.  https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/srv/salt/omv/deploy/apt/default.sls#L130

**Comment by ryecoaaron** [comment]
nevermind.  I see that change.  Not sure why the code worked for a long time.

**Comment by ryecoaaron** [comment]
Fix is here.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/c922a912c865d12fe8abcdae690b8822d55de6e8

I am pushing out the new package now.  People who have the new saltstack packages installed will have to install the update manually.  The install script will do that. Read the readme on https://github.com/OpenMediaVault-Plugin-Developers/packages

**Comment by jolu1705** [comment]
So install script should work now? I will give it a try in a minute.

**Comment by ryecoaaron** [comment]
Depends on the state of your system.  apt-get update  and then apt-get dist-upgrade should work unless omv-extras is in a bad state on your system.

**Comment by jolu1705** [comment]
No bad state here. Works like a charm atm.
I have installed several things from the repo to give it a try and so far I do not get any error messages.

Thanks for the fast help.

**Comment by ryecoaaron** [comment]
The problem that omvextras was having was only when it was trying to update apt after changing the omvextras repo list.  This wouldn't affect anything with apt or the omvextras repo.

**Comment by an0o0nym** [comment]
@ryecoaaron Quick question. How do I update omvextras on my OMV instance up to the version containing your fix? Do I just download from  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/openmediavault-omvextrasorg_latest_all5.deb and use OMV UI to install that file ? Or should I uninstall old version via OMV UI and only then proceed with new installation of omvextras?

**Comment by ryecoaaron** [comment]
@an0o0nym Go to the Updates tab, click Check, and install the update.

**Comment by kngharv** [comment]
@ryecoaaron : you freaking rock!  Thanks!

**Comment by votdev** [comment]
> The pkg.refresh_db function was removed from the latest saltstack packages Volker built.
> If he didn't remove the function (which is still shown in the docs [docs.saltproject.io/en/latest/ref/modules/all/salt.modules.aptpkg.html](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.aptpkg.html)), then I will have to come up with a solution that doesn't involve native salt code (not hard). The problem is people will have to manually install the update. What a mess.

The problem was that the latest Salt version does not like the old-style syntax of `module.run`. Sorry for that.
