### ISSUE TITLE
No function provided - OMV6

### ISSUE THREAD

**Issue by zAAmpie** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#58]
Hi,

This is the same issue reported previously in #55, but it seems it's back with OMV6 (shaitan) and the latest omvextras build grabbed via wget. I've followed the previous advice and updated everything, but still fails at the last step to do refresh_database_apt.

System is a new install on bare metal and fully upgraded. No issues with apt update and no updates available on any repo.

I may be doing something stupid.

Thanks for the help.

**Comment by zAAmpie** [comment]
I'm assuming [c922a91](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/c922a912c865d12fe8abcdae690b8822d55de6e8) did not make it into the newest 6.0 branch.

**Comment by ryecoaaron** [comment]
No, I will make the change.

**Comment by zAAmpie** [comment]
> No, I will make the change.

Thanks!

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/0c9826b24d5c0d5f02d7553573b6f2dad9c71e2a
6.0.1 is in the repo.

**Comment by zAAmpie** [comment]
Thanks ryecoaaron, confirmed working
