### ISSUE TITLE
[Feature] Add option to run Portainer with dark theme

### ISSUE THREAD

**Issue by Ansem93** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#59]
Hi,
it would be possible to have the option to start Portainer with a Dark theme? I would consider to add it in the advanced settings maybe.

There is a github with multiple skins:
https://docs.theme-park.dev/themes/portainer/
I don't think it's worth the effort to let users choose between multiple skins, I would be happy just with the dark one.
From the documentation ( https://docs.theme-park.dev/setup/ ) you just need add these two envrimoment variable:
DOCKER_MODS=ghcr.io/gilbn/theme.park:portainer
TP_THEME=dark

Portainer is basically the only thing that is still white :(

**Comment by ryecoaaron** [comment]
While I love dark mode, I would rather not use a non-portainer created theme as default because it could break on future upgrades.  All you need to do is start the container from the command line with your environment variables.

**Comment by ryecoaaron** [comment]
You could also use Yacht since dark mode is the default.

**Comment by skyajal** [comment]
Just to note that the environment options shared mostly apply to only linuxserver.io images. This also applies to images that support using docker mods. Portainer does not indicate they support this method. I tested this on my OMV arm system and there was no change to the theme even after clearing the cache for Firefox or Chrome. It looks like the nginx or stylus method would have to be tested to see if it would work. I don't think this is something to be considered as a feature for OMV but rather a discussion to have with the portainer devs to add dark theme support (which has been discussed for a long time now) or with the theme-park devs to provide some better documentation on how they implement their css for portainer.
