### ISSUE TITLE
plugin does not work

### ISSUE THREAD

**Issue by okpail** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#6]
openmediavault-omvextrasorg_latest_all-3.deb gives error

Failed to execute command 'export LANG=C; apt-get update 2>&1': Err http://ftp.nl.debian.org wheezy Release.gpg Something wicked happened resolving 'ftp.nl.debian.org:http' (-5 - No address associated with hostname) Err http://ftp.nl.debian.org wheezy-updates Release.gpg Something wicked happened resolving 'ftp.nl.debian.org:http' (-5 - No address associated with hostname) Err http://security.debian.org wheezy/updates Release.gpg Something wicked happened resolving 'security.debian.org:http' (-5 - No address associated with hostname) Ign file: Release.gpg Err http://packages.openmediavault.org kralizec Release.gpg Something wicked happened resolving 'packages.openmediavault.org:http' (-5 - No address associated with hostname) Ign http://ftp.nl.debian.org wheezy Release Ign http://security.debian.org wheezy/updates Release Ign file: Release Ign http://packages.openmediavault.org kralizec Release Ign http://packages.openmediavault.org kralizec/main amd64 Packages/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates Release Ign http://security.debian.org wheezy/updates/main Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy/main Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy/main amd64 Packages/DiffIndex Ign http://packages.openmediavault.org kralizec/partner amd64 Packages/DiffIndex Ign http://security.debian.org wheezy/updates/contrib Sources/DiffIndex Ign http://security.debian.org wheezy/updates/non-free Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/main Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/contrib Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/non-free Sources/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/main amd64 Packages/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/contrib amd64 Packages/DiffIndex Ign http://ftp.nl.debian.org wheezy-updates/non-free amd64 Packages/DiffIndex Ign http://security.debian.org wheezy/updates/main amd64 Packages/DiffIndex Ign http://security.debian.org wheezy/updates/contrib amd64 Packages/DiffIndex Ign http://security.debian.org wheezy/updates/non-free amd64 Packages/DiffIndex Err http://packages.openmediavault.org kralizec/main Translation-en Something wicked happened resolving 'packages.openmediavault.org:http' (-5 - No address associated with hostname) Err http://packages.openmediavault.org kralizec/main Translation-nl Something wicked happened resolving 'packages.openmediavault.org:http' (-5 - No address associated with hostname) Err http://packages.openmediavault.org kralizec/partner Translation-en Something wicked happen  etc.

**Comment by ryecoaaron** [comment]
You need to set your dns servers.
