### ISSUE TITLE
[Feature] : Allow selection of Portainer-CE or Portainer-EE

### ISSUE THREAD

**Issue by ptruman** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#63]
Portainer are now giving away free 5 node licences, for Portainer-EE (https://www.portainer.io/pricing/take5?utm_campaign=Five%20Nodes%20Free&utm_source=MOTD) - which adds a few nice features.

Switching image is detailed here (https://docs.portainer.io/v/ce-2.9/start/upgrade/tobe/docker) but then negates the handy "install Portainer" option from the OMV GUI.

Thought it may be handy to have a tickbox/drop down for which to install, so either could be maintained via one GUI rather than CLI :)

**Comment by ryecoaaron** [comment]
I think might be confusing for a lot of OMV users especially since you have to sign up to activate EE. What features of EE would be useful to OMV users?

**Comment by ptruman** [comment]
It could be, but OMV may well be in use in some small businesses, or people who want to orchestrate multiple nodes - ala the Proxmox support for those who run virtualised (or multi-node) envs.

Primarily it's better auth support (AD, LDAP, OAuth) and RBAC - but the full list is at https://www.portainer.io/blog/portainer-community-edition-ce-vs-portainer-business-pb-whats-the-difference

Worst case I can script a docker stop/docker rm/docker pull/docker run :)

**Comment by ryecoaaron** [comment]
I did look at the differences but I didn't really think those features would be needed for 99% of OMV users.  And people who do need them, can easily install portainer without the button.  It isn't hard to add the ability but I can still see many people ask which portainer version they would need on the forum.  Would adding an environment variable satisfy what you are looking for?

**Comment by ptruman** [comment]
Hi - it could well do as it's just a letter different to select the image:

portainer/portainer-ee:latest versus portainer/portainer-**c**e:latest

**Comment by PrplHaz4** [comment]
IMO the most useful EE features are `Force deployments to be in sync with the definition in Git` and AD/LDAP integration.  I have no plans to switch from CE to EE at this point.

A clear label on the dropdown for which to install may be enough:
- Portainer CE
- Portainer EE (Requires license key)

It's always a little uncomfortable when OSS projects bundle non-free services - but at it's core OMV is very useful to businesses so being a purist is probably not the right approach either.

**Comment by angeloschat** [comment]
One more vote for this feature.
For me the nicest feature is that now I can manage all my 3 OMV/Portainers from one main console.

**Comment by ryecoaaron** [comment]
EE in 6.0.4.  No more features will be added.
