### ISSUE TITLE
openmediavault/release-upgrade (5.x) scripts are not set executable

### ISSUE THREAD

**Issue by nrandon** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#65]
The following file are not set executable after an install of omvextrasog meaning during an upgrade the run-parts script ignore the files as there not exacuatable:

```
/usr/share/openmediavault/release-upgrade/post.d/60-omvextras-mergerfs
/usr/share/openmediavault/release-upgrade/pre.d/20-omvextras-sources-list
```

Think the error must be in the build stage somewhere are they are set executable in the 5.x repo.

To check that I not got a local issue I downloaded the deb (https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_5.6.5_all.deb) and expanded it using dpkg-deb and the file are not executable in the package and there is not method to set them executable i can see.

This currently make my test system not correctly update omvextrasorg as the source list dose not get updated. However it a simple fix post upgrade.

**Comment by ryecoaaron** [comment]
Not sure what happened.  They are executable in my local copy as well.  I rebuilt the package (5.6.6) and installed it.  They are executable after the install.
