### ISSUE TITLE
Photoprism plugin storage files over spill into /var/tmp

### ISSUE THREAD

**Issue by aldobranti** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#68]
This is OMV 6.0.18 with photoprism freshly installed from repo

Adding the photoprism service leads to a 50Gb pile of storagennnnn files into /var/tmp and blows up my small root disk
I previously set the storage in the UI to a shared dir on a disk where there is that kind of space

Despite podman claim to be CLI compatible with Docker, I cannot understand the systemd unit files
I am happy to try out and podman cli commands to help sort this

I had previously used docker to run photoprism on omv
`docker run   --name photoprism   --security-opt seccomp=unconfined   --security-opt apparmor=unconfined   -p 2342:2342   -e PHOTOPRISM_UPLOAD_NSFW=true   -e PHOTOPRISM_ADMIN_PASSWORD=redacted -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/PhotoPrismStorage:/photoprism/storage  -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/Pictures:/photoprism/originals photoprism/photoprism
pi@pi-vault:~/Docker/Photoprism $ docker run   --name photoprism   --security-opt seccomp=unconfined   --security-opt apparmor=unconfined   -p 2342:2342   -e PHOTOPRISM_UPLOAD_NSFW=true   -e PHOTOPRISM_ADMIN_PASSWORD=admin -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/PhotoPrismStorage:/photoprism/storage  -v /srv/dev-disk-by-label-DeskTop1Tb/ImageWillsMac/Pictures:/photoprism/originals photoprism/photoprism`

those storage locations are the one I selected for the photoprism config and there is enough space for the storage files

**Comment by ryecoaaron** [comment]
photoprism is a core OMV plugin.  So, the issue belongs here - https://github.com/openmediavault/openmediavault/issues/new/choose

**Comment by aldobranti** [comment]
thank you for the correction
