### ISSUE TITLE
Choose between portainer community and business edition

### ISSUE THREAD

**Issue by ThaMattie** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#73]
Is it possible to add a settings field for the Portainer image, so one can choose between portainer-ce and portainer-ee?
Perhaps defaulting to CE and a warning that the Business edition needs a license key to work.

**Comment by ryecoaaron** [comment]
Uh, this was added seven months ago.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/089b27abe3c9e4acb7bd17026e9d579fbfbdf307

![image](https://user-images.githubusercontent.com/1914475/174158041-9297b7b4-cf1a-4ede-b1b7-c4eff3db3ec9.png)

**Comment by ryecoaaron** [comment]
Yes. New features stopped being added to 5.x.
