### ISSUE TITLE
Portainer can't build image from repository because lack of git package

### ISSUE THREAD

**Issue by Monirzadeh** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#76]
​I try to build an image with portainer from repository, but failed.

In general, you should do these steps:

1. login to portainer

2. go to images > build a new image > URL

3. fill `name`,  `URL`,  ` Dockerfile path`​. Note : URL should use git repository with branch name, for example : `https://github.com/username/repository.git#master​`
4. press `Build the image`

You get fetal error and can't build the image.

More investigation show it happen because of git not install. This problem solves when i install git from terminal.

I think it is better omv-extra install git while install portainer to solve the bug and portainer became complete functional

UPDATE: I am not sure if this issue is in right repository, please move this if it is in wrong place and possible for you.
Or guild me for correct repository, please.

**Comment by ryecoaaron** [comment]
I don’t think it is omv-extras job to install every dependency that might be need for building docker images. If you need git, you can install it from the command line or from the apttool plugin. This is the first request in the years of omv-extras installing docker/portainer. So, it seems very few omv users using portainer need git.

**Comment by Monirzadeh** [comment]
> I don’t think it is omv-extras job to install every dependency that might be need for building docker images. If you need git, you can install it from the command line or from the apttool plugin. This is the first request in the years of omv-extras installing docker/portainer. So, it seems very few omv users using portainer need git.

It is to make portainer complete functional, but if you think it is not necessary, we can add that as a note for install portainer in documentation.
>If you need git, you can install it from the command line 

I review forum that multiple time warn users to not install program from command line.
You think it is not make any problem? (I think too, but I see multiple warning about that)

**Comment by ryecoaaron** [comment]
omv-extras only installs portainer to be helpful. Most people are not building images and if they are, they typically pull from github from command line, make changes, and then build. I don’t see how pulling and building without changes is very common to even warrant needing a note. If anything this should be in the portainer documentation not omv-extras.

I’m not sure where you read that you should never install anything from the command line. I also gave another option of installing from the apttool plugin. Either way, it would never be dangerous to install git. I have it installed on all of my omv systems.

**Comment by Monirzadeh** [comment]
Ok thanks
I close issue
