### ISSUE TITLE
Unable to change Docker storage path from UI

### ISSUE THREAD

**Issue by taai** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#77]
The Docker storage path is not changed when changing it in UI. The new input value is stored, but the data keeps being stored in the default path (```/var/lib/docker```).

Apparently you must have to have an existing file in ```/etc/docker/daemon.json```… If you do, the function works just fine. But in my fresh "Raspberry Pi OS" installation the file did not exist (even the directory ```/etc/docker``` didn't exist), even after changing the Docker storage path value in the UI.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/9a54f3cfca7377e667dbc5e55be0dcc6902da81a/usr/sbin/omv-installdocker#L320-L349

![image](https://user-images.githubusercontent.com/90734/216795227-f4fa8a35-db73-4c9e-a200-c512c51cf09e.png)

**Comment by ryecoaaron** [comment]
I can't reproduce this.  If you change the path and save, it may not be able to write the file at that moment.  But it will write the file immediately after installing docker via omv-extras - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/sbin/omv-installdocker#L404

If you are installing docker a different way, then you should not use the Docker tab in omv-extras.
