### ISSUE TITLE
Last update to 6.2 stuck at the migration script

### ISSUE THREAD

**Issue by muchachagrande** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#82]
The update was called from web interface and it stuck with these last messages:

Updating configuration database ...
Running migration conf.system.omvextras_6.2

I didn't do anything yet as I'm writing this issue while the update is still running.

**Comment by muchachagrande** [comment]
Now, when I try to access omv-extras menues I see:

![image](https://user-images.githubusercontent.com/20299175/230639530-787eec6c-1b56-45a0-83e1-c86c4bfe42b8.png)

**Comment by ryecoaaron** [comment]
This was fixed in 6.2.1.  I would also recommend not enabling the test repo.

**Comment by muchachagrande** [comment]
Ok, have disabled test repo. Thank you.
