### ISSUE TITLE
Problem with Installing openmediavault-omvextrasorg

### ISSUE THREAD

**Issue by matt7py** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#87]
Started with a fresh installation of openmediavault. Encountered issues during the installation of openmediavault-omvextrasorg.

I used this commend 
`wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
`
Via ssh I got some error 

root@OMV:~# wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
--2023-10-30 19:11:45--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install [following]
--2023-10-30 19:11:45--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [text/plain]
Saving to: ‘STDOUT’

-                                 100%[==========================================================>]   1.17K  --.-KB/s    in 0s      

2023-10-30 19:11:46 (24.9 MB/s) - written to stdout [1200/1200]

6
Downloading omv-extras.org plugin for openmediavault 6.x ...
Updating repos before installing...
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                    
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease                        
Hit:7 https://deb.debian.org/debian bullseye-backports InRelease                                    
Hit:8 https://packages.openmediavault.org/public shaitan InRelease
Reading package lists... Done
Install prerequisites...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gnupg : Depends: dirmngr (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: dirmngr (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gnupg-l10n (= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gnupg-utils (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gnupg-utils (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gpg (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gpg (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gpg-agent (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gpg-agent (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gpg-wks-client (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gpg-wks-client (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gpg-wks-server (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gpg-wks-server (>= 2.2.27-2+deb11u2) but it is not going to be installed
         Depends: gpgsm (< 2.2.27-2+deb11u2.1~) but it is not going to be installed
         Depends: gpgsm (>= 2.2.27-2+deb11u2) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
--2023-10-30 19:11:47--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master//openmediavault-omvextrasorg_latest_all6.deb
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all6.deb [following]
--2023-10-30 19:11:47--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all6.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45852 (45K) [application/octet-stream]
Saving to: ‘openmediavault-omvextrasorg_latest_all6.deb’

openmediavault-omvextrasorg_lates 100%[==========================================================>]  44.78K  --.-KB/s    in 0.03s   

2023-10-30 19:11:47 (1.55 MB/s) - ‘openmediavault-omvextrasorg_latest_all6.deb’ saved [45852/45852]

(Reading database ... 40585 files and directories currently installed.)
Preparing to unpack openmediavault-omvextrasorg_latest_all6.deb ...
Unpacking openmediavault-omvextrasorg (6.3.1) over (6.3.1) ...
dpkg: dependency problems prevent configuration of openmediavault-omvextrasorg:
 openmediavault-omvextrasorg depends on gnupg; however:
  Package gnupg is not installed.

dpkg: error processing package openmediavault-omvextrasorg (--install):
 dependency problems - leaving unconfigured
Processing triggers for openmediavault (6.5.0-3) ...
Restarting engine daemon ...
Errors were encountered while processing:
 openmediavault-omvextrasorg
Installing other dependencies ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  openmediavault-omvextrasorg
0 upgraded, 0 newly installed, 1 to remove and 5 not upgraded.
1 not fully installed or removed.
After this operation, 521 kB disk space will be freed.
(Reading database ... 40583 files and directories currently installed.)
Removing openmediavault-omvextrasorg (6.3.1) ...
Processing triggers for openmediavault (6.5.0-3) ...
Restarting engine daemon ...
Updating workbench configuration files ...
Updating repos ...
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release                           
Ign:2 file:/var/cache/openmediavault/archives  Release                           
Get:3 file:/var/cache/openmediavault/archives  Packages                                           
Ign:3 file:/var/cache/openmediavault/archives  Packages                                           
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                     
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                     
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                  
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                  
Get:3 file:/var/cache/openmediavault/archives  Packages                                           
Ign:3 file:/var/cache/openmediavault/archives  Packages                                           
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                     
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                     
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                  
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                  
Get:3 file:/var/cache/openmediavault/archives  Packages                                           
Ign:3 file:/var/cache/openmediavault/archives  Packages                                           
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Ign:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Get:3 file:/var/cache/openmediavault/archives  Packages                                                                             
Get:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Ign:4 file:/var/cache/openmediavault/archives  Translation-en                                                                       
Get:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Ign:5 file:/var/cache/openmediavault/archives  Translation-en_US                                                                    
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease                                                        
Hit:7 https://deb.debian.org/debian bullseye-backports InRelease                                                                    
Hit:8 https://packages.openmediavault.org/public shaitan InRelease                                                 
Reading package lists... Done
root@OMV:~# 

But the option does not appear :(

![Screenshot 2023-10-30 at 7 14 37 PM](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/assets/120527800/745e0a02-940c-43e2-9e37-d0ff4392975b)

**Comment by ryecoaaron** [comment]
You must have installed OMV without internet because you are missing the main debian repo. Please search or post on the forum for help fixing this. There are many threads on it.

**Comment by matt7py** [comment]
I've already taken care of that. I unplugged the Ethernet cable during the installation and then reconnected it. If I hadn't done that, the screen would freeze, making it impossible to complete the installation.

However, now I'm facing this issue. Can you help me?

**Comment by ryecoaaron** [comment]
sigh… https://forum.openmediavault.org/index.php?thread/45998-can-t-install-omv-extras/&pageNo=2
