### ISSUE TITLE
404 error when trying to update openmediavault-omvextrasorg

### ISSUE THREAD

**Issue by knw257** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#88]
It appears that the domain openmediavault-plugin-developers.github.io is returning a 404 error for all requests. This is a problem because it is the main update repository domain for the omvextras project, based on the omv-aptclean script used by the main DEB package, according to this line: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/2c35e6ecafb7b530599b8b0fcb44a6cab0a9f308/usr/sbin/omv-aptclean#L60

Either the line should be changed to a working URL, or the github.io page should be fixed so that it provides the proper packages.

**Comment by ryecoaaron** [comment]
I'm not seeing any errors when running apt-get update.  That is the correct url for the github hosted repo.  Has the repo worked for you in the past?  Maybe you hit the repo when it was being updated?

**Comment by knw257** [comment]
Here's the error message I received when trying to update openmediavault-omvextrasorg through the update manager:

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=[C.UTF](http://C.UTF)\-8; export LANGUAGE=; apt-get --yes --allow-downgrades --allow-change-held-packages --download-only --reinstall install 'openmediavault-omvextrasorg' 2>&1' with exit code '100': Reading package lists...  
 Building dependency tree...  
 Reading state information...  
 The following packages will be upgraded:  
   openmediavault-omvextrasorg  
 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.  
 Need to get 47.5 kB of archives.  
 After this operation, 16.4 kB of additional disk space will be used.  
 Err:1 [https://openmediavault-plugin-developers.github.io/packages/debian](http://C.UTF) shaitan/main amd64 openmediavault-omvextrasorg all 6.3.4  
   404  Not Found \[IP: [185\.199.111.153](http://185.199.111.153) 443\]  
 E: Failed to fetch [https://openmediavault-plugin-developers.github.io/packages/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_6.3.4_all.deb](http://C.UTF)  404  Not Found \[IP: [185\.199.111.153](http://185.199.111.153) 443\]  
 E: Some files failed to download

OMV\\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=[C.UTF](http://C.UTF)\-8; export LANGUAGE=; apt-get --yes --allow-downgrades --allow-change-held-packages --download-only --reinstall install 'openmediavault-omvextrasorg' 2>&1' with exit code '100': Reading package lists...  
 Building dependency tree...  
 Reading state information...  
 The following packages will be upgraded:  
   openmediavault-omvextrasorg  
 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.  
 Need to get 47.5 kB of archives.  
 After this operation, 16.4 kB of additional disk space will be used.  
 Err:1 [https://openmediavault-plugin-developers.github.io/packages/debian](http://C.UTF) shaitan/main amd64 openmediavault-omvextrasorg all 6.3.4  
   404  Not Found \[IP: [185\.199.111.153](http://185.199.111.153) 443\]  
 E: Failed to fetch [https://openmediavault-plugin-developers.github.io/packages/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_6.3.4_all.deb](http://C.UTF)  404  Not Found \[IP: [185\.199.111.153](http://185.199.111.153) 443\]  
 E: Some files failed to download in /usr/share/php/openmediavault/system/[process.inc:242](http://process.inc:242)  
 Stack trace:  
 #0 /usr/share/openmediavault/engined/rpc/[apt.inc](http://apt.inc)(351): OMV\\System\\Process->execute()  
 #1 /usr/share/php/openmediavault/rpc/[serviceabstract.inc](http://serviceabstract.inc)(620): Engined\\Rpc\\Apt->Engined\\Rpc\\{closure}('/tmp/bgstatusL2...', '/tmp/bgoutputRy...')  
 #2 /usr/share/openmediavault/engined/rpc/[apt.inc](http://apt.inc)(405): OMV\\Rpc\\ServiceAbstract->execBgProc(Object(Closure))  
 #3 \[internal function\]: Engined\\Rpc\\Apt->getChangeLog(Array, Array)  
 #4 /usr/share/php/openmediavault/rpc/[serviceabstract.inc](http://serviceabstract.inc)(123): call_user_func_array(Array, Array)  
 #5 /usr/share/php/openmediavault/rpc/[rpc.inc](http://rpc.inc)(86): OMV\\Rpc\\ServiceAbstract->callMethod('getChangeLog', Array, Array)  
 #6 /usr/sbin/omv-engined(537): OMV\\Rpc\\Rpc::call('Apt', 'getChangeLog', Array, Array, 1)  
 #7 {main}
``` 

When I try to access the specific URL being attempted here [https://openmediavault-plugin-developers.github.io/packages/debian/pool/main/o/openmediavault-omvextrasorg/openmediavault-omvextrasorg_6.3.4_all.deb](url), or just access [https://openmediavault-plugin-developers.github.io](url), I receive a 404 error
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/assets/11547080/216ceb79-d4f6-4365-a43d-1b127722a6ae)
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/assets/11547080/bbb7e05b-db96-4ade-8825-0cd21eeb9f2b)

**Comment by ryecoaaron** [comment]
The site isn't supposed to be browsed by browser.  But it looks like your network is blocking the dns.  I know China blocks github and a mirror has to be used for omv and omv-extras.

Just tested on my system.

Get:9 https://openmediavault-plugin-developers.github.io/packages/debian sandworm InRelease [3,936 B]                                                          
...
Get:12 https://openmediavault.github.io/packages sandworm InRelease [12.8 kB]                                                                                  
...
Get:31 https://openmediavault-plugin-developers.github.io/packages/debian sandworm/main amd64 Packages [8,206 B]
...
Get:34 https://openmediavault.github.io/packages sandworm/main amd64 Packages [7,678 B]
...
Get:43 http://packages.openmediavault.org/public sandworm/main amd64 Packages [7,678 B]
Fetched 25.7 MB in 4s (7,125 kB/s)

**Comment by ryecoaaron** [comment]
and on my omv6 system

Get:9 https://openmediavault.github.io/packages shaitan InRelease [12.8 kB]
Get:11 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease [3,934 B]
Get:14 http://packages.openmediavault.org/public shaitan InRelease [12.8 kB]
Get:28 https://openmediavault.github.io/packages shaitan/main amd64 Packages [13.7 kB]
Get:36 https://openmediavault-plugin-developers.github.io/packages/debian shaitan/main amd64 Packages [9,375 B]
Get:39 http://packages.openmediavault.org/public shaitan/main amd64 Packages [13.7 kB]

**Comment by knw257** [comment]
I'm going from my OMV system, here's what happens when I try to curl the URL directly:

```
# wget --spider --debug https://openmediavault-plugin-developers.github.io/packages/debian/
DEBUG output created by Wget 1.21 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'index.html' (UTF-8) -> 'index.html' (UTF-8)
Spider mode enabled. Check if remote file exists.
--2023-12-30 15:33:00--  https://openmediavault-plugin-developers.github.io/packages/debian/
Certificates loaded: 129
Resolving openmediavault-plugin-developers.github.io (openmediavault-plugin-developers.github.io)... 185.199.108.153, 185.199.111.153, 185.199.110.153, ...
Caching openmediavault-plugin-developers.github.io => 185.199.108.153 185.199.111.153 185.199.110.153 185.199.109.153 2606:50c0:8000::153 2606:50c0:8003::153 2606:50c0:8002::153 2606:50c0:8001::153
Connecting to openmediavault-plugin-developers.github.io (openmediavault-plugin-developers.github.io)|185.199.108.153|:443... connected.
Created socket 3.
Releasing 0x000055d26124b970 (new refcount 1).

---request begin---
HEAD /packages/debian/ HTTP/1.1
User-Agent: Wget/1.21
Accept: */*
Accept-Encoding: identity
Host: openmediavault-plugin-developers.github.io
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 9379
Server: GitHub.com
Content-Type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
Access-Control-Allow-Origin: *
ETag: "64d39a40-24a3"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
x-proxy-cache: MISS
X-GitHub-Request-Id: 4728:7499:1200A1F:17FFA68:65907E63
Accept-Ranges: bytes
Date: Sat, 30 Dec 2023 20:33:00 GMT
Via: 1.1 varnish
Age: 22
X-Served-By: cache-bos4662-BOS
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1703968380.216659,VS0,VE1
Vary: Accept-Encoding
X-Fastly-Request-ID: cc96e8e28b63ee41d53d123fa198f42bc00ba04b

---response end---
404 Not Found
Registered socket 3 for persistent reuse.
URI content encoding = ‘utf-8’
Remote file does not exist -- broken link!!!
```

And when I try apt update:
```
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease
Hit:7 http://deb.debian.org/debian bullseye InRelease
Get:8 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Hit:9 https://download.docker.com/linux/debian bullseye InRelease
Hit:10 https://openmediavault.github.io/packages shaitan InRelease
Hit:11 https://openmediavault-plugin-developers.github.io/packages/debian shaitan InRelease
Get:12 http://httpredir.debian.org/debian bullseye-backports InRelease [49.0 kB]
Hit:13 http://packages.openmediavault.org/public shaitan InRelease
```

Out of curiosity, what IP does openmediavault-plugin-developers.github.io resolve to for you? Perhaps there's an issue with the github server I'm hitting, and you're hitting a different server without issues?

**Comment by ryecoaaron** [comment]
Your apt update output looks fine and it is accessing the repo.  Here are the IPs from two different systems in different cities:

$ ping -c2 openmediavault-plugin-developers.github.io
PING openmediavault-plugin-developers.github.io (185.199.110.153) 56(84) bytes of data.

$ ping -c2 openmediavault-plugin-developers.github.io
PING openmediavault-plugin-developers.github.io (185.199.108.153) 56(84) bytes of data.

**Comment by knw257** [comment]
Okay, looks like it only responds to specific URLs correctly, so my attempt to manually test these URLs was in vain. After realizing this, I manually tried to download the .deb file, and it worked for me, so I'm closing this out as a weird transient issue
