### ISSUE TITLE
omvextrasorg_latest_all7.deb 404 not found

### ISSUE THREAD

**Issue by felix9ia** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#89]
run 
```
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash

```
But i got 

https://github.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all7.deb 404 not found

not 

https://github.com/OpenMediaVault-Plugin-Developers/packages/blob/master/openmediavault-omvextrasorg_latest_all7.deb

================================================================================
= OS/Debian information
================================================================================
Distributor ID: Debian
Description: Armbian 23.11.1 bookworm
Release: 12
Codename: bookworm

================================================================================
= openmediavault information
================================================================================
Release: 7.0-29
Codename: Sandworm

**Comment by ryecoaaron** [comment]
Not sure why you are having the issue.  I just tested and it is working on my end.  Maybe a temporary github mirror issue?

aaron@omv7dev:/srv/plugins$ ./install
OMV 7
Codename :: bookworm
Downloading omv-extras.org plugin for openmediavault 7.x ...
--2024-02-12 07:45:23--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master//openmediavault-omvextrasorg_latest_all7.deb
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all7.deb [following]
--2024-02-12 07:45:23--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/openmediavault-omvextrasorg_latest_all7.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40672 (40K) [application/octet-stream]
Saving to: ‘openmediavault-omvextrasorg_latest_all7.deb’

openmediavault-omvextrasorg_latest_ 100%[===================================================================>]  39.72K  --.-KB/s    in 0.02s   

2024-02-12 07:45:23 (1.78 MB/s) - ‘openmediavault-omvextrasorg_latest_all7.deb’ saved [40672/40672]

**Comment by ryecoaaron** [comment]
The script is using this url to download it:
https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/openmediavault-omvextrasorg_latest_all7.deb

**Comment by felix9ia** [comment]
This seems to be a github cache issue, I'm very sorry
